apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# commonLabels:
#   prometheus: k8s
# namespace: monitoring #this nees to be set, otherwise config may end up in current active namespace
bases:
  - https://github.com/prometheus-operator/kube-prometheus.git?ref=release-0.7
patchesStrategicMerge:
  - patches/prometheus-clusterRole.yaml  
  - patches/grafana-deployment.yaml
  # - patches/prometheus-prometheus.yaml
