---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux
  namespace: flux
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux
  url: ssh://git@github.com/Modulus/flux-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux
  namespace: flux
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  validation: client
